version: 0.1
env:
  variables:
    PACKAGE: "wallet-lambda-go"
phases:
  install:
    commands:
      - env
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"

  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - go get -t ./...

  build:
    commands:
      - go build -o main

  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket wallet.lambda
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - '**/*'