version: 0.1
env:
  variables:
    PACKAGE: "wallet-lambda-go"
phases:
  install:
    commands:
      - mkdir -p ${GOPATH}/src/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${GOPATH}/src/${PACKAGE}
      - go get github.com/aws/aws-lambda-go/events
      - go get github.com/aws/aws-lambda-go/lambda
      - go get github.com/jinzhu/gorm/dialects/mysql
      - go get github.com/jinzhu/inflection
  build:
    commands:
      - go build -o main

  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket wallet.lambda
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - '**/*'