version: 0.1
env:
  variables:
    PACKAGE: "wallet-lambda-go"
phases:
  install:
    commands:
      - mkdir -p "/go/src/wallet-lambda-go"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/wallet-lambda-go"

  pre_build:
    commands:
      - cd "/go/src/wallet-lambda-go" && go get -t ./...

  build:
    commands:
      - go build -o main

  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket wallet.lambda
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - '**/*'