AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handle wallet operations
Parameters:
  DBName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBName
  DBMasterUserName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBMasterUserName
  DBMasterPassword:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: WalletDBMasterPassword
Resources:
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./
      Events:
        DefaultApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /wallet
            Method: GET
      Environment:
        Variables:
          DB_ENDPOINT_ADDRESS: !ImportValue WalletDBEndpoint
          DB_PORT: !ImportValue WalletDBPort
          DB_NAME: !Ref DBName
          DB_USERNAME: !Ref DBMasterUserName
          DB_PASSWORD: !Ref DBMasterPassword
          DB_DRIVER: mysql
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yaml
      StageName: v1
      Variables:
        ListFunctionName: !Ref ListFunction