AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handle wallet operations

Resources:
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./
      Events:
        DefaultApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /wallet
            Method: GET

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yaml
      StageName: v1
      Variables:
        ListFunctionName: !Ref ListFunction